### ISSUE TITLE
Create New Release / Tag

### ISSUE THREAD

**Issue by dsposito** [embedly/embedly-php#25]
Can you please create a new release with the latest code changes so devs can pull it in via composer? The last one is from February 2015.

Thanks!

**Comment by dokipen** [comment]
Can you give me exact instructions? I haven't touched this in years and I'm not a PHP dev. I forget what to do.

**Comment by dsposito** [comment]
@dokipen Sure, you can use GitHub's UI to create a new release.

Tag Version: v0.5.6 @ Target: master
Release Title: v0.5.6

**Comment by dokipen** [comment]
Just tag it? That's it?

**Comment by dsposito** [comment]
Yep, thanks! This way I can specify the new v0.5.6 tag in my composer.json so it'll pull in the most recent changes. I'll test it out this week and confirm that it's working.

**Comment by dokipen** [comment]
Awesome. I'll be working until Thursday, then I'll be off until Jan 3rd.

**Comment by dsposito** [comment]
Tested - worked great. Thank you!
